### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by dobbse42** [alexandrupaler/arithmetic#2]
- [x] write ctrladd function
- [ ] move qubit creation to separate function
- [x] fix ancillary qubit location
- [x] write pseudocode for the multiplier
- [x] implement pseudocode
- [x] write testing code (displays two summands and sum, two factors and product)
